before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: JEWe7IDJkJTykL9HSY23ZP+Be7njlLyDSLyIpPnmPevXEwqd5GCNUO/cYEAMsz3IZfbdzCifQLDwlxozKbE8OhJWlNtlqbsZ43nHdNOoeg6zcarPf24sud0Q2S0Q4b+yWfMUvS/pv/42fHfNQjlwERjyg8TPLZgRjsVjhCxqeXYPVbz8XEJ4WV9rjyrcY0xySyO1w8Z0HGHEWAUyYZ6JkuN4mz9YOsJgur49uJBml5xmNRZxYnvxDdeW29Bdw4KlhEE+8qLy4GztNnXm9CfXy/g4qKuecWvVbGR6JwzDyujgMfJFVeNsPTW5JTR4/PfUXfGE/6JdHsIWHpr+qYAzHza8u3mWIKhm3t3J6cfcL2DbTNjF1236escRqo1h+PqQUzfHOnP0mJkoy3ckRqbg+IuZhYW+sEJHAuRJxtXdvnd4EAh7VhwaFgBeqA9FrvGdZH5rMVahORvDxnJyOawJxDtc21UNqqreyTWyNf+T719S8QgZbrmwBOwLwnIkA1llj2PAracSMmopzflwxXGQrs2jEeXGSHKgTsQtOSi0bjbA07vjgUAFZW/X1NryS+szAcSrH6OXg7JtQZGhhK5N/9lvWbRQm4gKqaGKNiDEHa91UsrDb9q82HvomSVVPe7nMANk6l/isZjQCWL3wYTowxci3PWyjufQZ193RN3kLls= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
